### ISSUE TITLE
Able to re/double buy pepe. Buying a pepe at your own pepe collection.

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#4] opened 2018-06-12 09:33 UTC
# Buying a pepe at your own pepe collection.

After buying or bidding on a pepe and getting 2 tx confirms. pepe shows up at my pepes. Once i click on the pepe in this case 103. https://dev.cryptopepes.io/pepe/103
It says Its not mine, but its for sale and there is a buy button. 

### Affected parts

- [x] Backend API: search/lookups
- [ ] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [x] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Accounts used

Seller : 0x1086c166eF05fB94A969696Aae491CdB22ECc316
Me. buyer: 0x892b85B5a6412e12E749A94D3e0b9fe519C4a032

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

Metamask,

### Steps to reproduce

1. Bid on pepe.
2. Go to my pepes
3. Click on new bought pepe.

**Comment by programmerror** [comment] 2018-06-12 15:27
The sale/owner info is behind (Slow DB update time + propagation of the mined TX). I will update to use Web3 here if available. The issue is a little bad for UX, but the smartcontract will ensure that actual 2nd buys won't go through, and fail.

**Comment by programmerror** [comment] 2018-06-13 19:49
Seeing this as part of a larger issue, so I created #30. You can continue discussion there if you want. Closing this issue now.

**Closed as completed by programmerror** 2018-06-13 19:49 UTC
