### ISSUE TITLE
no web3 on opening link in new tab using MMB

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#12] opened 2018-06-12 10:45 UTC
# no web3 on opening link in new tab using MMB

Page gives the following error.
![image](https://user-images.githubusercontent.com/7458738/41285958-3116180a-6e3e-11e8-8b34-3581c8ad3211.png)
When opening a new tab using middle mouse button. for example my pepes.

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [x] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [x] Miscellaneous

### Common questions

> Check the boxes that apply

- [x] Logged in?
- [ ] Recently switched accounts?
- [ ] Do you use multiple accounts at the same time?

> Answer briefly, if relevant

**Which Web3 wallet do you use?**

Metamask, + Chrome + Windows10

### Steps to reproduce

1. login metamask. as usual.
2. open page in new tab using middle mouse button. 
3. get error no-web3.

**Comment by programmerror** [comment] 2018-06-13 22:12
Fixed, the problem is that the my-pepes link needs to communicate with web3 to get the default address. However, at the time of loading a new page, web3 isn't loaded. Now it will redirect to the portfolio as soon as web3 is loaded. Fixed in next release :+1:

**Closed as completed by programmerror** 2018-06-13 22:12 UTC
