### ISSUE TITLE
"never hopped"

### ISSUE THREAD

**Issue by rayhvh** [CryptoPepes/cryptopepes-alpha-test#11] opened 2018-06-12 10:38 UTC
#  neverhopped

Update time is either really slow or not working on amount of times or last time hopped.
My pepe 103. That has been hopped 15+ minutes ago. Is not updating hopped status. 

### Affected parts

- [ ] Backend API: search/lookups
- [x] Frontend: Visual
- [ ] Frontend: interactions
- [ ] Smartcontract: CPEP erc271
- [ ] Smartcontract: Cozy auction
- [ ] Smartcontract: Sale auction
- [ ] Smartcontracts - miscellaneous
- [ ] Miscellaneous

### Steps to reproduce

1. hop pepe (103)
2.  go to my pepe 15 min later. click on pepe
3.  shows never hopped. still shows children.

**Comment by programmerror** [comment] 2018-06-12 15:41
This looks like a caching issue in the API, we're going to change it to use web3 to query/update values more eagerly when possible.

**Comment by programmerror** [comment] 2018-06-13 20:38
This turns out to be something in the backend not updating till the next full backfill, which takes long indeed. See #21, and #29. Closing this, the issue is being worked on and a fix will get into next release.

**Closed as completed by programmerror** 2018-06-13 20:38 UTC
